
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class leavereq extends javax.swing.JFrame {

    /**
     * Creates new form leavereq
     */
    static String eid,aid,va;
    public leavereq(String id,String a) {
        aid=a;
        eid=id;
        initComponents();
        String header[]={"Leave Id","Employee Id","Leave Code","From Date","To Date","Number of Days","Leaves Left","Date Applied","Purpose","Email","Status"};
        String val[][]={};
        DefaultTableModel model=new DefaultTableModel();
        model.setDataVector(val, header);
        jTable2.setModel(model);
        try
        {
            lblEid.setText(eid);
            
         Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
         Connection con=DriverManager.getConnection("Jdbc:odbc:abc");
         Statement st=con.createStatement();
         ResultSet rs=st.executeQuery("select * from leaves where emp_id='"+eid+"'");
         
             
         while(rs.next())
         {
             String v1=rs.getString(1);
             String v2=rs.getString(2);
             String v3=rs.getString(3);
             String v4=rs.getString(4);
             String v5=rs.getString(5);
             String v6=rs.getString(6);
             String v7=rs.getString(7);
             String v8=rs.getString(8);
             String v9=rs.getString(9);
             String v10=rs.getString(10);
             String v12=rs.getString(12);
             String row[]={v1,v2,v3,v4,v5,v6,v7,v8,v9,v10,v12};
             model.addRow(row);
             jTable2.setModel(model);
             
         }
         
         
        }
        catch(Exception e)
        {
            System.out.println("Error Because of "+e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        lblEid = new javax.swing.JLabel();
        btnSanction = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.jpeg"))); // NOI18N
        jLabel4.setText("BACK");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        btnSanction.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSanction.setText("SANCTION");
        btnSanction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSanctionActionPerformed(evt);
            }
        });

        btnReject.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnReject.setText("REJECT");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEid, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 510, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSanction, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(btnReject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnSanction, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnReject, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
new empdet(eid,aid).setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void btnSanctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSanctionActionPerformed
        try{
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
         Connection con=DriverManager.getConnection("Jdbc:odbc:abc");
         Statement st=con.createStatement();
         ResultSet rs = st.executeQuery("select * from leaves where leave_id='" + va + "'");
         if(rs.next())
         {
             String lcode=rs.getString(3);
         String status=rs.getString(12); 
         int ndays=Integer.parseInt(rs.getString(6));
         int lbal=Integer.parseInt(rs.getString(7));
         
         if(status.equals("SANCTIONED")||status.equals("REJECTED"))
         {
         JOptionPane.showMessageDialog(rootPane, "Already "+status);
         }
         else
         {
          int bal=lbal-ndays;
          st.executeUpdate("update leaves SET status='SANCTIONED' where leave_id='"+va+"'");
          st.executeUpdate("update leaves SET leave_left="+bal+" where emp_id='"+eid+"'");
          if(lcode.equals("CL"))
             {
             st.executeUpdate("update details SET CL='"+bal+"' where emp_id='"+eid+"'");
             }
             else if(lcode.equals("VL"))
             {
             st.executeUpdate("update details SET VL='"+bal+"' where emp_id='"+eid+"'");
             }
          JOptionPane.showMessageDialog(rootPane, "SANCTIONED");
         }
         }
        }
        catch(Exception ex)
        {
            System.out.println("Error because of "+ex);
            ex.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSanctionActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        try{
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
         Connection con=DriverManager.getConnection("Jdbc:odbc:abc");
         Statement st=con.createStatement();
         ResultSet rs = st.executeQuery("select * from leaves where leave_id='" + va + "'");
         if(rs.next())
         {
             
         String status=rs.getString(12); 
         
         if(status.equals("SANCTIONED")||status.equals("REJECTED"))
         {
         JOptionPane.showMessageDialog(rootPane, "Already "+status);
         }
         else
         {
          st.executeUpdate("update leaves SET status='REJECTED' where leave_id='"+va+"'");
          
          JOptionPane.showMessageDialog(rootPane, "REJECTED");
         }
         }
        }
        catch(Exception ex)
        {
            System.out.println("Error because of "+ex);
        }
    }//GEN-LAST:event_btnRejectActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked

        int row=jTable2.getSelectedRow();
        int col=jTable2.getSelectedColumn();
        va=jTable2.getValueAt(row, col).toString();        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(leavereq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(leavereq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(leavereq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(leavereq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new leavereq(eid,aid).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReject;
    private javax.swing.JButton btnSanction;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblEid;
    // End of variables declaration//GEN-END:variables
}
